import type { Category } from "@/models/category.model";

export const categories: Category[] = [
  {
    id: "1",
    categoryName: "Food",
    color: "#FF6384",
    icon: "utensils",
    type: "expense",
    isDefault: true,
    createdAt: new Date(),
  },
  {
    id: "2",
    categoryName: "Transport",
    color: "#36A2EB",
    icon: "car",
    type: "expense",
    isDefault: true,
    createdAt: new Date(),
  },
  {
    id: "3",
    categoryName: "Shopping",
    color: "#FFCE56",
    icon: "shopping-bag",
    type: "expense",
    isDefault: true,
    createdAt: new Date(),
  },
  {
    id: "4",
    categoryName: "Entertainment",
    color: "#4BC0C0",
    icon: "film",
    type: "expense",
    isDefault: true,
    createdAt: new Date(),
  },
  {
    id: "5",
    categoryName: "Health",
    color: "#9966FF",
    icon: "heartbeat",
    type: "expense",
    isDefault: true,
    createdAt: new Date(),
  },
  {
    id: "6",
    categoryName: "Utilities",
    color: "#FF9F40",
    icon: "bolt",
    type: "expense",
    isDefault: true,
    createdAt: new Date(),
  },
  {
    id: "7",
    categoryName: "Salary",
    color: "#00C49F",
    icon: "money-bill-wave",
    type: "income",
    isDefault: true,
    createdAt: new Date(),
  },
  {
    id: "8",
    categoryName: "Freelance",
    color: "#0088FE",
    icon: "laptop-code",
    type: "income",
    isDefault: true,
    createdAt: new Date(),
  },
  {
    id: "9",
    categoryName: "Gifts",
    color: "#FFBB28",
    icon: "gift",
    type: "income",
    isDefault: true,
    createdAt: new Date(),
  },
  {
    id: "10",
    categoryName: "Other",
    color: "#C0C0C0",
    icon: "ellipsis-h",
    type: "expense",
    isDefault: true,
    createdAt: new Date(),
  },
];
